image: debian:unstable

before_script:
  - apt update -qq
  - apt install -y -qq build-essential meson pkg-config gtk-doc-tools
                       libxml2-utils gobject-introspection dbus
                       libglib2.0-dev libgtk-3-dev appstream-util
                       desktop-file-utils lcov gettext
  - export LANG=C.UTF-8

stages:
  - build

build-and-test:
  stage: build
  script:
    - meson --buildtype debug --werror _build .
    - ninja -C _build
    - ninja -C _build test
  except:
    - tags
  artifacts:
    when: on_failure
    name: "hitori-_${CI_COMMIT_REF_NAME}"
    paths:
      - "${CI_PROJECT_DIR}/_build/meson-logs"

# FIXME: Run gtkdoc-check when we can. See:
# https://github.com/mesonbuild/meson/issues/3580