stages:
  - build
  - deploy

build-and-test:
  stage: build
  image: debian:unstable
  before_script:
    - apt update -qq
    - apt install -y -qq build-essential meson pkg-config gtk-doc-tools
                         libxml2-utils gobject-introspection dbus
                         libglib2.0-dev libgtk-3-dev appstream
                         desktop-file-utils lcov gettext itstool
    - export LANG=C.UTF-8
  script:
    - meson --buildtype debug --werror _build .
    - ninja -C _build
    - ninja -C _build test
  except:
    - tags
  artifacts:
    when: on_failure
    name: "hitori-_${CI_COMMIT_REF_NAME}"
    paths:
      - "${CI_PROJECT_DIR}/_build/meson-logs"

# FIXME: Run gtkdoc-check when we can. See:
# https://github.com/mesonbuild/meson/issues/3580

# flatpak nightly support
include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

variables:
    BUNDLE: "hitori-dev.flatpak"

flatpak:
  stage: build
  variables:
    MANIFEST_PATH: "flatpak/org.gnome.Hitori-unstable.json"
    FLATPAK_MODULE: "hitori"
    RUNTIME_REPO: "https://sdk.gnome.org/gnome-nightly.flatpakrepo"
    APP_ID: "org.gnome.Hitori"
  extends: .flatpak

nightly:
    extends: '.publish_nightly'
    dependencies: ['flatpak']
    needs: ['flatpak']
